language: ruby

rvm:
  - jruby-19mode
  - ree
  - 1.8.7
  - 1.9.3
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile

sudo: false

notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails42.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails41.gemfile
    - rvm: ree
      gemfile: gemfiles/rails42.gemfile
    - rvm: ree
      gemfile: gemfiles/rails41.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/rails32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails32.gemfile
